### PR TITLE
Distribute JWT from New

### PR DESCRIPTION
**Pull request by itleigns**
## Context

Currently, New function of API obtains jwt, and we need to set up a mock server when testing the New function. Furthermore, given the definition, getting an API does not include getting a JWT. So we want to separate the JWT acquisition from New function to make test easier.

## Objective

To separate the JWT acquisition from New function.

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by cappyzawa** [comment]
You might want to execute `go mod tidy`.

**Comment by itleigns** [comment]
Thank you. I fixed it as you said.

**Review by kkokufud — APPROVED** [review]
LGTM

**Review by MysticDoll — APPROVED** [review]
lgtm :)

**Review by tkyi — APPROVED** [review]

**Pull request merged**
